import React from 'react';
import './globals.css';

export const metadata = {
	title: 'Miguel\'s Portfolio',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body>{children}</body>
		</html>
	);
}
